version: '3.5'

services:
  vertica:
    image: jbfavre/vertica:9.x
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '4'
          memory: 4G
