version: '3.5'

services:
  cassandra:
      image: cassandra:4.1
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always

  cassandra-load-keyspace:
      container_name: cassandra-load-keyspace
      image: cassandra:4.1
      depends_on:
        - cassandra
      volumes:
        - ./schema.cql:/schema.cql
      command: /bin/bash -c "sleep 120 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
