name: UGC stuff

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.7'] #, '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html

      - name: Lint with flake8
        run: flake8 . --format=html --htmldir=./public

      - name: Deploy lint report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            See ${{ github.workflow }} [linter report](https://srsamoylenko.github.io/ugc_sprint_1)
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.7'] #, '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock

      - name: Lint with flake8
        run: python -m pytest